### ISSUE TITLE
Update-SM365Ruleset (Ruleset Update CmdLet )

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmail365#11]
As SEPPmail continues to adapt and refine the rulset, based on customer feedback, the Module shall offer an option to update the current ruleset to a defined of the latest version. If a ruleset applies to a specific SMA-Version, the user shall have the option to deploy the ruleset for that specific SMA version.

Example:

Update-SM365Rulse

**Comment by MDomhardt** [comment]
Ist umgesetzt auf dem Branch pre-release
