### ISSUE TITLE
ConfigValidierung "Options" wirft Fehler

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmail365#35]
Deser Befehl: 
"New-SM365Connectors -SEPPmailFQDN securemail.test.com _-Option AntiSpamWhiteList_

Erzeugt diesen Fehler:
ForEach-Object: /Users/roman/GitRepo/SEPPmail365/Private/PrivateFunctions.ps1:98:52
Line |
  98 |              $Json.Version.$_.psobject.properties | ForEach-Object{
     |                                                     ~~~~~~~~~~~~~~~
     | The property '' cannot be found on this object. Verify that the property exists and can be set.

**Comment by MDomhardt** [comment]
Sollte gefixt sein, war ein peinlicher Vertipper.
Teste bitte mal und schließ das Ticket wenn alles funktioniert.

**Comment by RStadlmair** [comment]
Done
