### ISSUE TITLE
Get-SM365Connectors -Version Parameter throws error on value "None"

### ISSUE THREAD

**Issue by RStadlmair** [seppmail/SEPPmail365#47]
... because its a string.

PS /Users/monty/SEPPmail> Get-SM365Connectors                                                                           
Connected to Exchange Organization "seppmail365.de" 
Get-SM365InboundConnectorSettings: /Users/monty/.local/share/powershell/Modules/SEPPMail365/1.2.2/Public/Connectors.ps1:24
Line |
  24 |          $inbound = Get-SM365InboundConnectorSettings -Version "None" 
     |                                                                ~~~~~~
     | Cannot process argument transformation on parameter 'Version'. Cannot convert value "None" to type "SM365.ConfigVersion". Error: "Unable to match the
     | identifier name None to a valid enumerator name. Specify one of the following enumerator names and try again: Default, Latest" 

Get-SM365OutboundConnectorSettings: /Users/monty/.local/share/powershell/Modules/SEPPMail365/1.2.2/Public/Connectors.ps1:25
Line |
  25 |  …        $outbound = Get-SM365OutboundConnectorSettings -Version "None" 
     |                                                                   ~~~~~~
     | Cannot process argument transformation on parameter 'Version'. Cannot convert value "None" to type "SM365.ConfigVersion". Error: "Unable to match the
     | identifier name None to a valid enumerator name. Specify one of the following enumerator names and try again: Default, Latest" 

WARNING: Es ist mindestens ein testmodusconnector vorhanden, der nicht im Ergebnis enthalten ist. Verwenden Sie-IncludeTestModeConnectors, um den testmodusverbinder anzuzeigen.
WARNING: No SEPPmail Outbound Connector with name "" found
WARNING: No SEPPmail Inbound Connector with Name "" found
PS /Users/monty/SEPPmail>

**Comment by bendingunit** [comment]
same here:

Remove-SM365Setup
Connected to Exchange Organization "acme.org"

                        Remove-TransportRule -id $rule -Confirm:$false


                        Remove-TransportRule -id $rule -Confirm:$false


                        Remove-TransportRule -id $rule -Confirm:$false


                        Remove-TransportRule -id $rule -Confirm:$false

Connected to Exchange Organization "acme.org"
Remove-SM365Connectors : Cannot process argument transformation on parameter 'Version'. Cannot convert value "None" to type "SM365.ConfigVersion". Error: "Unable to match the identifier name None to a valid enumerator name. Specify one of the following enumerator names and try
again:
Default, Latest"
At C:\Program Files\WindowsPowerShell\Modules\SEPPmail365\1.2.2\Public\Common.ps1:211 char:9
+         Remove-SM365Connectors
+         ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Remove-SM365Connectors], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Remove-SM365Connectors

**Comment by bendingunit** [comment]
and here:

```

 Get-SM365Connectors
Connected to Exchange Organization "acme.org"
Get-SM365InboundConnectorSettings : Cannot process argument transformation on parameter 'Version'. Cannot convert value "None" to type "SM365.ConfigVersion". Error: "Unable to match the identifier name None to a valid enumerator name. Specify one of the following enumerator
names and try again:
Default, Latest"
At C:\Program Files\WindowsPowerShell\Modules\SEPPmail365\1.2.2\Public\Connectors.ps1:24 char:63
+         $inbound = Get-SM365InboundConnectorSettings -Version "None"
+                                                               ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-SM365InboundConnectorSettings], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-SM365InboundConnectorSettings

Get-SM365OutboundConnectorSettings : Cannot process argument transformation on parameter 'Version'. Cannot convert value "None" to type "SM365.ConfigVersion". Error: "Unable to match the identifier name None to a valid enumerator name. Specify one of the following enumerator
names and try again:
Default, Latest"
At C:\Program Files\WindowsPowerShell\Modules\SEPPmail365\1.2.2\Public\Connectors.ps1:25 char:65
+ ...        $outbound = Get-SM365OutboundConnectorSettings -Version "None"
+                                                                    ~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-SM365OutboundConnectorSettings], ParameterBindingArgumentTransformationException
    + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-SM365OutboundConnectorSettings

WARNING: There is at least one test mode connector which is not included in the result. Please use -IncludeTestModeConnectors to view test mode connectors.
WARNING: No SEPPmail Outbound Connector with name "" found
WARNING: No SEPPmail Inbound Connector with Name "" found
```
